export interface BcegMotoContrat {
    id: number
    emf_id: number

    // Identité contrat
    type_contrat: string
    police_numero: string
    visas_dna: string

    // Couverture (prêt)
    numero_police: string // Unique identifier generated by backend
    montant_pret: number
    duree_pret: number // mois
    date_effet: string // YYYY-MM-DD
    date_fin_echeance: string // YYYY-MM-DD

    // Souscripteur / Personne assurée
    nom: string
    prenom: string
    ville: string
    adresse_telephone: string

    // Engin
    marque_type_engin: string
    valeur_assuree: number
    immatriculation: string

    // Paramètres prime
    // Optional fields
    statut?: string // e.g. 'En attente', 'Actif'
    categorie?: string // e.g. 'Standard'

    taux_prime_unique: number
    prime_deces_invalidite: number
    cotisations_complementaires: number
    prime_totale: number
    devise: string

    created_at?: string
    updated_at?: string
    deleted_at?: string
}

export interface BcegMotoContratFormData {
    emf_id: number

    // Couverture
    montant_pret: number
    duree_pret: number
    date_effet: string
    date_fin_echeance: string

    // Assuré
    nom: string
    prenom: string
    ville: string
    adresse_telephone: string

    // Engin
    marque_type_engin?: string
    valeur_assuree?: number | null
    immatriculation?: string

    // Optionnel
    taux_prime_unique?: number
    cotisations_complementaires?: number
    devise?: string
    statut?: string
    categorie?: string
}

export interface BcegMotoCalculResult {
    montant_pret: number
    forfait_garanties_complementaires: number
    taux_prime_unique: number
    prime_deces_invalidite: number
    prime_totale: number
    formule: string
    plafond_montant_pret: number
}
